# Generated by Django 3.2.13 on 2023-02-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='like_users',
            new_name='like_articles',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_users',
            new_name='like_comment',
        ),
    ]
